### ISSUE TITLE
add CookiesConsent form

### ISSUE THREAD

**Issue by juanArias8** [Monadical-SAS/Morpheus#9]
`CookiesConset.tsx`

```typescript
import { useEffect } from "react";
import { useAnalytics } from "../../context/AnalyticsProvider";
import { deleteAllCookies } from "../../utils/cookies";
import useLocalStorage from "../../hooks/useLocalStorage";
import styles from "./CookiesConsent.module.scss";

const CookiesConsent = () => {
  const { cookiesStatus, setCookiesStatus } = useAnalytics();

  const [localCookies, setLocalCookies] = useLocalStorage("cp:cookies", null);
  const finalStatus = localCookies || cookiesStatus || "";

  useEffect(() => {
    if (localCookies !== "") setCookiesStatus(localCookies);
  }, [localCookies]);

  const handleActionCookies = (event: any, status: string) => {
    event.preventDefault();

    if (status === "decline") {
      deleteAllCookies();
    }

    setCookiesStatus(status);
    setLocalCookies(status);
  };

  return finalStatus === "" ? (
    <div className={styles.cookiesContainer}>
      <div className={styles.textContainer}>
        <p className="heading white">
          This website uses cookies to ensure you get the best experience on our
          website.
          <a target="_blank" href="">
            Privacy Policy
          </a>
        </p>
      </div>

      <div className={styles.buttonsSection}>
        <button
          className="buttonSubmit"
          onClick={(event) => handleActionCookies(event, "declined")}
        >
          Decline
        </button>

        <button
          className="buttonSubmit"
          onClick={(event) => handleActionCookies(event, "accepted")}
        >
          Accept
        </button>
      </div>
    </div>
  ) : null;
};

export default CookiesConsent;
```

`CookiesConset.module.scss`
```css
@import "styles/main";

.cookiesContainer {
  position: fixed;
  bottom: 0;
  left: 0;
  width: 100vw;
  min-height: 50px;
  height: auto;
  z-index: 999;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: rgba(0, 0, 0, 0.9);
  padding: 20px;

  @include phone {
    flex-direction: column;
    justify-content: flex-start;
  }

  .textContainer {
    width: 70%;
    height: 100%;
    display: flex;
    align-items: center;

    a {
      display: block;
      text-decoration: underline;
    }

    @include phone {
      width: 100%;
      flex-direction: column;
      align-items: flex-start;
    }
  }

  .buttonsSection {
    width: auto;
    margin-left: 24px;
    display: flex;
    justify-content: space-between;
    min-width: 400px;
    padding-right: 24px;

    @include phone {
      width: 100%;
      flex-direction: column;
      margin: 24px 0 0 0;
    }

    button {
      :first-child {
        margin-right: 24px !important;
      }

      @include phone {
        width: 100%;
        margin: 8px !important;
      }
    }
  }
}
```

`/utils/cookies.ts`
```typescript
const deleteAllCookies = () => {
  const cookies = document.cookie.split(";");

  for (let i = 0; i < cookies.length; i++) {
    const cookie = cookies[i];
    const eqPos = cookie.indexOf("=");
    const name = eqPos > -1 ? cookie.substr(0, eqPos) : cookie;
    document.cookie = name + "=;expires=Thu, 01 Jan 1970 00:00:00 GMT";
  }
};

export { deleteAllCookies };
```
